name: alzheimer-drug-ml
channels:
  - bioconda
  - rdkit
  - mordred
  - conda-forge
dependencies:
  - python=3.7
  - jupyter
  - pip
  - rdkit
  - mordred
  - pip:
     - git+https://github.com/samoturk/mol2vec
     - -r requirements.txt
    
